"use client";
import {useEffect,useMemo,useState} from "react";
import * as XLSX from "xlsx";
type Rate={date:string,rate:number}; type Pay={date:string,amount:number};
const source="https://www.bankofengland.co.uk/boeapps/database/Bank-Rate.asp";
const fallback:Rate[]=[["2023-08-03",5.25],["2024-08-01",5],["2024-11-07",4.75],["2025-02-06",4.5],["2025-05-08",4.25],["2025-08-07",4],["2025-12-18",3.75]].map(x=>({date:String(x[0]),rate:Number(x[1])}));
const D=(s:string)=>new Date(s+"T00:00:00Z"), I=(d:Date)=>d.toISOString().slice(0,10), plus=(d:Date,n:number)=>new Date(d.getTime()+n*864e5);
function month(d:Date,n:number){const x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+n,1)),last=new Date(Date.UTC(x.getUTCFullYear(),x.getUTCMonth()+1,0)).getUTCDate();x.setUTCDate(Math.min(d.getUTCDate(),last));return x}
const gbp=(n:number)=>n.toLocaleString("en-GB",{style:"currency",currency:"GBP"});
function parse(csv:string){const lines=csv.replace(/^\uFEFF/,"").trim().split(/\r?\n/),head=lines[0].toLowerCase(),start=/date|amount|payment/.test(head)?1:0;return lines.slice(start).map(l=>{const c=l.split(",").map(x=>x.replace(/["£\s]/g,"")),raw=c[0],date=/^\d{2}\/\d{2}\/\d{4}$/.test(raw)?`${raw.slice(6)}-${raw.slice(3,5)}-${raw.slice(0,2)}`:I(new Date(raw));return{date,amount:Number(c[1].replace(/,/g,""))}}).filter(x=>Number.isFinite(x.amount))}
function calc(principal:number,discount:number,start:string,end:string,timing:string,rates:Rate[],pays:Pay[]){
 const out:Record<string, string|number>[]=[],s=D(start),e=D(end),hasCsv=pays.length>0; let p=principal,unpaid=0,previous:number|null=null;
 for(let i=0,from=s;from<=e;i++,from=month(s,i)){let to=plus(month(s,i+1),-1);if(to>e)to=e;const days=Math.round((+to-+from)/864e5)+1;let interest=0,baseSum=0;
  for(let x=new Date(from);x<=to;x=plus(x,1)){const r=rates.filter(q=>q.date<=I(x)).at(-1)?.rate||0;baseSum+=r;interest+=p*Math.max(0,r+discount)/100/365}
  const found=pays.filter(q=>D(q.date)>=from&&D(q.date)<=to),actual=found.reduce((a,b)=>a+b.amount,0);
  const payment=found.length?actual:!hasCsv?interest:previous??interest;
  const kind=found.length?"CSV":!hasCsv?"Calculated interest":previous!==null?"Previous month":"Calculated interest (before first CSV)";
  previous=payment;
  const ip=Math.min(payment,unpaid+interest),pp=Math.min(p,Math.max(0,payment-ip));unpaid=Math.max(0,unpaid+interest-ip);const close=p-pp;
  out.push({Period:i+1,From:I(from),To:I(to),"Due date":timing==="advance"?I(from):I(to),Days:days,"Opening principal":p,"Average Bank Rate":baseSum/days/100,"Loan rate":(baseSum/days+discount)/100,"Interest charged":interest,Payment:payment,"Payment source":kind,"Interest paid":ip,"Principal paid":pp,"Unpaid interest":unpaid,"Closing principal":close,"Closing balance":close+unpaid});p=close;if(to>=e)break;
 } return out
}
export default function Home({ canExport = false }: { canExport?: boolean }){
 const [principal,setPrincipal]=useState(100000),[discount,setDiscount]=useState(-1.5),[start,setStart]=useState("2023-12-19"),[end,setEnd]=useState(I(new Date())),[timing,setTiming]=useState("arrears"),[rates,setRates]=useState(fallback),[pays,setPays]=useState<Pay[]>([]),[file,setFile]=useState("No CSV selected"),[status,setStatus]=useState("Checking official source…");
 useEffect(()=>{fetch("/api/bank-rate").then(r=>r.json()).then(x=>{setRates(x.rates);setStatus(x.live?"Official history retrieved online":"Verified official history (offline fallback)")}).catch(()=>setStatus("Verified official history (offline fallback)"))},[]);
 const rows=useMemo(()=>calc(principal,discount,start,end,timing,rates,pays),[principal,discount,start,end,timing,rates,pays]),last=rows.at(-1),interest=rows.reduce((a,r)=>a+r["Interest charged"],0),paid=rows.reduce((a,r)=>a+r.Payment,0);
 function upload(f?:File){if(!f)return;f.text().then(t=>{const p=parse(t);setPays(p);setFile(`${f.name} · ${p.length} rows`)})}
 function exportXlsx(){const wb=XLSX.utils.book_new(),ass=[["LOAN STATEMENT"],["Principal",principal],["Bank Rate source",source],["Discount",discount/100],["Start date",start],["End date",end],["Interest timing",timing],["Convention","Actual/365; daily weighted Bank Rate; monthly anniversary periods"],["No CSV","Assume each month's calculated interest was paid"],["Missing CSV month","Repeat the previous month's payment"],["Before first CSV payment","Assume the calculated monthly interest was paid"],["Waterfall","Accrued interest first, then principal"]],a=XLSX.utils.aoa_to_sheet(ass),s=XLSX.utils.json_to_sheet(rows),p=XLSX.utils.json_to_sheet(pays.length?pays:[{date:"",amount:""}]),r=XLSX.utils.json_to_sheet(rates.map(x=>({date:x.date,rate:x.rate/100,source})));a["!cols"]=[{wch:24},{wch:74}];s["!cols"]=Object.keys(rows[0]||{}).map(()=>({wch:18}));XLSX.utils.book_append_sheet(wb,a,"Assumptions");XLSX.utils.book_append_sheet(wb,s,"Monthly Statement");XLSX.utils.book_append_sheet(wb,p,"Payments");XLSX.utils.book_append_sheet(wb,r,"Bank Rate History");XLSX.writeFile(wb,`loan-statement-${start}-to-${end}.xlsx`)}
 return <main><header><div><p className="eyebrow">PRIVATE LOAN · MONTHLY STATEMENT</p><h1>Loan Statement Calculator</h1><p>Auditable interest-only statements using official Bank of England Bank Rate history.</p></div><aside><small>Current Bank Rate</small><strong>{rates.at(-1)?.rate.toFixed(2)}%</strong><small>effective {rates.at(-1)?.date}</small></aside></header>
 <div className="grid"><section className="controls"><h2><i>01</i> Loan terms</h2><label>Principal (£)<input type="number" value={principal} onChange={e=>setPrincipal(+e.target.value)}/></label><label>Interest rate discount (%)<input type="number" step=".01" value={discount} onChange={e=>setDiscount(+e.target.value)}/></label><div className="dates"><label>Start date<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End date<input type="date" min={start} value={end} onChange={e=>setEnd(e.target.value)}/></label></div><fieldset><legend>Interest charged</legend><label><input type="radio" checked={timing==="arrears"} onChange={()=>setTiming("arrears")}/> In arrears</label><label><input type="radio" checked={timing==="advance"} onChange={()=>setTiming("advance")}/> In advance</label></fieldset><div className="rate"><b>● Bank Rate history</b><span>{status}</span><a href={source} target="_blank">View official source ↗</a></div><h2><i>02</i> Payments</h2><label className="upload"><input type="file" accept=".csv" onChange={e=>upload(e.target.files?.[0])}/><b>Choose payment CSV</b><span>{file}</span></label><p className="note">CSV columns: date, amount. Without a CSV, each month defaults to its calculated interest. With a CSV, an absent loan month repeats the previous month’s payment; before the first CSV payment, calculated interest is assumed.</p>{canExport && <button onClick={exportXlsx}>Export Excel statement <span>↗</span></button>}</section>
 <section className="results"><div className="cards"><article><span>Closing balance</span><strong>{gbp(last?.["Closing balance"]||principal)}</strong><small>Principal + unpaid interest</small></article><article><span>Interest charged</span><strong>{gbp(interest)}</strong><small>{rows.length} periods</small></article><article><span>Payments applied</span><strong>{gbp(paid)}</strong><small>{pays.length} actual CSV rows</small></article><article><span>Unpaid interest</span><strong>{gbp(last?.["Unpaid interest"]||0)}</strong><small>At {end}</small></article></div><div className="table"><div className="title"><div><p className="eyebrow">CALCULATED STATEMENT</p><h2>Monthly movement</h2></div><span>Actual/365 · daily rate weighting</span></div><div className="scroll"><table><thead><tr>{["Period","Dates","Bank Rate","Loan rate","Interest","Payment","Source","Unpaid interest","Principal","Balance"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.Period}><td>{r.Period}</td><td>{r.From}<br/><small>to {r.To}</small></td><td>{(r["Average Bank Rate"]*100).toFixed(3)}%</td><td>{(r["Loan rate"]*100).toFixed(3)}%</td><td>{gbp(r["Interest charged"])}</td><td>{gbp(r.Payment)}</td><td><em className={r["Payment source"]==="CSV"?"actual":""}>{r["Payment source"]}</em></td><td>{gbp(r["Unpaid interest"])}</td><td>{gbp(r["Closing principal"])}</td><td><b>{gbp(r["Closing balance"])}</b></td></tr>)}</tbody></table></div></div><div className="method"><b>Calculation convention</b><span>Monthly periods follow the loan anniversary date. Interest is simple interest on principal, calculated daily at Bank Rate plus the discount. Payments clear accrued interest first; excess reduces principal. “Advance” changes the due date, not the historical interest amount.</span></div></section></div></main>
}
